spring.application.name=Prometheus
server.port=8081
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
sqlitedb.path=prome.db
spring.datasource.url=jdbc:sqlite:${sqlitedb.path}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jooq.sql-dialect=org.hibernate.community.dialect.SQLiteDialect